import {
  Tv,
  Music,
  Sparkles,
  PlayCircle,
  Music2,
  Cloud,
  HardDrive,
  Folder,
  Gamepad2,
  Gamepad,
  Smartphone,
  Phone,
  Signal,
  Radio,
  Disc,
  Briefcase,
  Palette,
  Github,
  Linkedin,
  Video,
  Mountain,
  MoreHorizontal,
  Circle,
  LucideIcon,
  Feather,
  Film,
  Disc3,
  CloudLightning,
  Cpu,
  Zap,
  Package,
  FileText,
  Layout,
  Figma,
  CheckCircle,
  MessageCircle,
  Bookmark,
  CheckSquare,
  Trello,
  Calendar,
  MessageSquare,
  Users,
  BookOpen,
  Book,
  Globe,
  GraduationCap,
  Award,
  Star,
  Lightbulb,
  Shield,
  ShieldCheck,
  Lock,
  Key,
  Smile,
  Activity,
  Bike,
  Heart,
  Utensils,
  Dumbbell,
  Newspaper,
  Headphones,
  Car,
  ShoppingBag,
  ShoppingCart,
  Mail,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  tv: Tv,
  music: Music,
  sparkles: Sparkles,
  'play-circle': PlayCircle,
  'music-2': Music2,
  youtube: Video,
  'tv-2': Tv,
  cloud: Cloud,
  'hard-drive': HardDrive,
  folder: Folder,
  'gamepad-2': Gamepad2,
  gamepad: Gamepad,
  smartphone: Smartphone,
  phone: Phone,
  signal: Signal,
  tower: Radio,
  disc: Disc,
  'disc-3': Disc3,
  briefcase: Briefcase,
  palette: Palette,
  github: Github,
  linkedin: Linkedin,
  video: Video,
  mountain: Mountain,
  'more-horizontal': MoreHorizontal,
  circle: Circle,
  feather: Feather,
  film: Film,
  'cloud-lightning': CloudLightning,
  cpu: Cpu,
  zap: Zap,
  package: Package,
  'file-text': FileText,
  layout: Layout,
  figma: Figma,
  'check-circle': CheckCircle,
  'message-circle': MessageCircle,
  bookmark: Bookmark,
  'check-square': CheckSquare,
  trello: Trello,
  calendar: Calendar,
  'message-square': MessageSquare,
  users: Users,
  'book-open': BookOpen,
  book: Book,
  globe: Globe,
  'graduation-cap': GraduationCap,
  award: Award,
  star: Star,
  lightbulb: Lightbulb,
  shield: Shield,
  'shield-check': ShieldCheck,
  lock: Lock,
  key: Key,
  smile: Smile,
  activity: Activity,
  bike: Bike,
  heart: Heart,
  utensils: Utensils,
  dumbbell: Dumbbell,
  newspaper: Newspaper,
  headphones: Headphones,
  car: Car,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  mail: Mail,
};

export const getIconComponent = (iconName: string): LucideIcon => {
  return iconMap[iconName] || Circle;
};
